"""add_indexes

Revision ID: 3e8a4db4cf66
Revises: ce10d8bcb384
Create Date: 2026-03-29 16:05:17.111734
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8a4db4cf66'
down_revision = 'ce10d8bcb384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipeline_jobs_status'), 'pipeline_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_rescue_cases_geocode_status'), 'rescue_cases', ['geocode_status'], unique=False)
    op.create_index(op.f('ix_rescue_cases_rescue_status'), 'rescue_cases', ['rescue_status'], unique=False)
    op.create_index(op.f('ix_rescue_cases_severity'), 'rescue_cases', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rescue_cases_severity'), table_name='rescue_cases')
    op.drop_index(op.f('ix_rescue_cases_rescue_status'), table_name='rescue_cases')
    op.drop_index(op.f('ix_rescue_cases_geocode_status'), table_name='rescue_cases')
    op.drop_index(op.f('ix_pipeline_jobs_status'), table_name='pipeline_jobs')
    # ### end Alembic commands ###
