"""add_address_fields

Revision ID: ce10d8bcb384
Revises: 0001_init
Create Date: 2026-03-29 09:05:08.905224
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce10d8bcb384'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescue_cases', sa.Column('ward_commune', sa.String(length=255), nullable=True))
    op.add_column('rescue_cases', sa.Column('district_extracted', sa.String(length=255), nullable=True))
    op.add_column('rescue_cases', sa.Column('province', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rescue_cases', 'province')
    op.drop_column('rescue_cases', 'district_extracted')
    op.drop_column('rescue_cases', 'ward_commune')
    # ### end Alembic commands ###
